---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gol
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gameoflife
  template:
    metadata:
      labels:
        app: gameoflife
    spec:
      containers:
      - name: gameoflife
        image: dockersing/gameoflife:1.0
        ports:
        - containerPort: 8080
          protocol: TCP